### ISSUE TITLE
ACPI not working

### ISSUE THREAD

**Issue by zdimension** [CosmosOS/Cosmos#114]
On my new OS, I'm trying to implement ACPI using the class from dewitcher (that was working on older releases) but the problem is that with this :
```csharp
public static void Shutdown()
{
    Console.Clear();
    if (PM1a_CNT == null) Init();
    if (pm1aIO != null)
    {
        pm1aIO.Word = (ushort)(SLP_TYPa | SLP_EN);
        if (PM1b_CNT != null)
            pm1bIO.Word = (ushort)(SLP_TYPb | SLP_EN);
    }
    Console.WriteLine("Its now safe to turn off the computer.");
}
```
I get a compilation error :
```
Error occurred while invoking IL2CPU.
Exception: System.NotImplementedException: Or on types 'System.UInt16' and 'System.Int16' not yet implemented!
   … Cosmos.IL2CPU.ILOpCodes.OpNone.DoInterpretStackTypes(Boolean& aSituationChanged) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILOpCodes\OpNone.cs:ligne 723
   … Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:ligne 384
   … Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:ligne 436
   … Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:ligne 430
   … Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:ligne 412
   … Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:ligne 389
   … Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:ligne 436
   … Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:ligne 430
   … Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:ligne 412
   … Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:ligne 389
   … Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:ligne 436
   … Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:ligne 430
   … Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:ligne 412
   … Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:ligne 389
   … Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:ligne 436
   … Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:ligne 430
   … Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:ligne 412
   … Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:ligne 389
   … Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:ligne 698
   … Cosmos.IL2CPU.AppAssembler.EmitInstructions(MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:ligne 541
   … Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:ligne 503
   … Cosmos.IL2CPU.ILScanner.Assemble() dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:ligne 941
   … Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:ligne 257
   … Cosmos.IL2CPU.CompilerEngine.Execute() dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:ligne 238
```
(SLP_TYPa, SLP_TYPb and SLP_EN are of type ```short```)
So I tried to cast them to ```ushort``` like that :
```csharp
public static void Shutdown()
{
    Console.Clear();
    if (PM1a_CNT == null) Init();
    if (pm1aIO != null)
    {
        pm1aIO.Word = (ushort)((ushort)SLP_TYPa | (ushort)SLP_EN);
        if (PM1b_CNT != null)
            pm1bIO.Word = (ushort)((ushort)SLP_TYPb | (ushort)SLP_EN);
    }
    Console.WriteLine("Its now safe to turn off the computer.");
}
```
Now I get this error :
```
Error occurred while invoking IL2CPU.
Exception: System.Exception: Wrong Poptype encountered! (Type = System.UIntPtr, expected = System.Byte*)
   … Cosmos.IL2CPU.ILOpCodes.OpField.DoInterpretStackTypes(Boolean& aSituationChanged) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILOpCodes\OpField.cs:ligne 225
   … Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:ligne 384
   … Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:ligne 436
   … Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:ligne 430
   … Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:ligne 412
   … Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:ligne 389
   … Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:ligne 436
   … Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:ligne 430
   … Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:ligne 412
   … Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:ligne 389
   … Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:ligne 698
   … Cosmos.IL2CPU.AppAssembler.EmitInstructions(MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:ligne 541
   … Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:ligne 511
   … Cosmos.IL2CPU.ILScanner.Assemble() dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:ligne 941
   … Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:ligne 257
   … Cosmos.IL2CPU.CompilerEngine.Execute() dans d:\Documents\GitHub\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:ligne 238
```
I think it's a bug or something like that.
Thanks

Full code for **ACPI.cs** [here](http://dewitcher.codeplex.com/SourceControl/latest#Core/ACPI.cs)

**Comment by mterwoord** [comment]
It's a bug in our IL interpreter. You could easily fix it yourself. Using the ECMA 335, you can find out what the poptype should be (first error). Second error is a similar error, but not because of an unimplemented case, but because of a wrongly implemented one. Could you have a look? I'm available for tutoring.. :)

**Comment by mterwoord** [comment]
First bug is fixed now.

**Comment by Oj18** [comment]
This still doesn't work :/

**Comment by jp2masa** [comment]
What doesn't work?

**Comment by Oj18** [comment]
The code above

**Comment by Oj18** [comment]
ACPI.cs
I'm using that code too, still getting that first error.

**Comment by jp2masa** [comment]
Are you using the userkit or the devkit?

**Comment by valentinbreiz** [comment]
You have a working ACPI.cs here https://github.com/CosmosOS/Cosmos/pull/633/commits

**Comment by Oj18** [comment]
I have an ACPI code
The exact same as the above.
User kit :/

**Comment by Oj18** [comment]
What's the difference?

**Comment by valentinbreiz** [comment]
Between devkit and userkit ?

**Comment by Oj18** [comment]
Yes

**Comment by valentinbreiz** [comment]
Devkit is the compilated code of Cosmos and userkit is an Installer.
Devkit is better to use because you have all new updates

**Comment by Oj18** [comment]
Oh, damn. How easy is it to switch?

**Comment by valentinbreiz** [comment]
Download the source code from github and run the install-VS2015.bat file if you use Visual Studio 2015 or install-VS2015.bat if you use VS2017

**Comment by Oj18** [comment]
What? install-VS2015 for VS 2015 and install-VS2015 for VS 2017??

**Comment by valentinbreiz** [comment]
I edited my comment sorry :/
If you need to use Cosmos with Visual Studio 2017, download the netcore branch.

**Comment by Oj18** [comment]
Why do I need dev kit, all it is is the source code

**Comment by Oj18** [comment]
Oh sweet you can use it with VS 2017 then

**Comment by valentinbreiz** [comment]
You have to compilate the source code :P

**Comment by Oj18** [comment]
Compilate?

**Comment by valentinbreiz** [comment]
Build if you prefer

**Comment by Oj18** [comment]
What? Wait so I run install-VS2017.bat?

**Comment by Oj18** [comment]
After installing all the prerequisets and already the user kit?

**Comment by valentinbreiz** [comment]
Yes !

**Comment by valentinbreiz** [comment]
You don't need the userkit, the userkit will be deleted and the devkit installed avec the "build" of Cosmos

**Comment by Oj18** [comment]
Oh ok.

**Comment by Oj18** [comment]
Where do I download it in that tree?

**Comment by valentinbreiz** [comment]
Here https://image.noelshack.com/fichiers/2017/23/7/1497206568-capture.png

**Comment by Oj18** [comment]
Oh, the whole thing ok then run install-VS2017 which is where?

**Comment by valentinbreiz** [comment]
Extract the ZIP and run the bat xD

**Comment by Oj18** [comment]
Ok. Thanks, my Wifi is very bad, will report back after it has downloaded. Thanks for all this btw :)

**Comment by Oj18** [comment]
About to start install, just run install-VS2017, right?
Making sure for the final time, definatly doesn't matter about the user kit being installed?

**Comment by valentinbreiz** [comment]
Yes

**Comment by Oj18** [comment]
Ok, installing now, then my code should just work?

**Comment by valentinbreiz** [comment]
That, I don't know, I just explained you how to install devkit xD

**Comment by jp2masa** [comment]
@Oj18 You need to change the target framework from 4.5 to 4.5.2, you can create a new project and copy your code to it, or change the framework in the project properties and editing the Cosmos project.

**Comment by Oj18** [comment]
Ok, Visual Studio has to install and download more stuff though. This will take long. Then I will install the dev kit, will report in like half an hour or something.

**Comment by Oj18** [comment]
Long story short, visual studio installer crashed whilst updating, have to download it again. :(

**Comment by zdimension** [comment]
Oh wow, I just received 39 mails from GitHub showing me replies to my long forgotten 2015 (the good ol' Cosmos days) post here. 
Well it seems Cosmos has got a lot of new features since then, and it seems that ACPI is supported out of the box now. I'm too lazy to download the latest [user|dev]kit and test on my computer, if someone could tell me if ACPI works now, so I can close this issue.

**Comment by Oj18** [comment]
Oh, sorry about the emails :D
I'll look up how then, thanks
