### ISSUE TITLE
DHCP Discover fails

### ISSUE THREAD

**Issue by Kiirx** [CosmosOS/Cosmos#2096]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Networking

#### Expected Behaviour - What do you think that should happen?
DHCP and Manual configuration should work

#### Actual Behaviour - What unexpectedly happens?
CPU exception with random address error

#### Reproduction - How did you get this error to appear?
do a DHCP connection like in the documentation it wont work, there's even no DHCP request that is even made from the CosmosOS 
(its not me because its happening to someone else and also on AuraOS but it was woking previously)

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
last devkit

**Comment by Kiirx** [comment]
This should be a high priority issue

**Comment by Kiirx** [comment]
so this is defenitly a cosmos issue

**Comment by abjdev** [comment]
try older version of cosmos devkit. _sended by .net framework_

**Comment by Kiirx** [comment]
no?

**Comment by abjdev** [comment]
try this: 
```csharp
using (var xClient = new DHCPClient())
            {
                try
                {
                    NetworkDevice nic = NetworkDevice.GetDeviceByName("eth0"); //get network device by name
                    IPConfig.Enable(nic, new Address(192, 168, 1, 69), new Address(255, 255, 255, 0), new Address(192, 168, 1, 254)); //enable IPv4 configuration
                    Console.WriteLine("Done! u have this: " + NetworkConfig.CurrentConfig.Value.IPAddress.ToString());
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.ToString());
                }
            }
```

**Comment by Kiirx** [comment]
dude.... stop this... u keep not listening 
> Ok so apparently, by removing the Cosmos external debugger DHCP requests are made but I stil get errors from my try catch

**Comment by valentinbreiz** [comment]
Hello @Kiirx if you're saying the DHCP request is made, I will need you to send me a save of the wireshark network trafic to see what cause the issue in Cosmos. It's maybe an issue with your router and Cosmos because for me it's still working fine.

**Comment by Kiirx** [comment]
Hi, I fixed it, but I still only have 0.0.0.0

**Comment by poggingfish** [comment]
Hello, i have a similar problem. Whenever i make a request to DHCP i get the IP 0.0.0.0 (aka the request failed)

**Comment by poggingfish** [comment]
Tested in both AuraOS and my os. 
I am not on my computer right now but after i get on i will tell you what cosmos version i was using and the code.

**Comment by poggingfish** [comment]
> Hello @poggingfish,
> 
> Same as @Kiirx to investigate what's causing the issue I need you to send me a capture of the network traffic once the DHCP request is sent.

Yes, i can send you the capture in a few hours

**Comment by Kiirx** [comment]
![image](https://user-images.githubusercontent.com/43090601/152844886-4b46c471-a41a-43a2-b4ed-0dca55998863.png)

**Comment by valentinbreiz** [comment]
Perfect, could you send me the .pcap file? (File -> Save)

**Comment by Kiirx** [comment]
the manual connection do work

**Comment by poggingfish** [comment]
When using bridged I am actually seeing no DHCP activity...
Strange?

**Comment by poggingfish** [comment]
[pcap.zip](https://github.com/CosmosOS/Cosmos/files/8019048/pcap.zip)
This should be it. Just search for DHCP.

**Comment by Kiirx** [comment]
try without debugger @poggingfish

**Comment by poggingfish** [comment]
Yes i did. I now have the DHCP information in the pcap

**Comment by poggingfish** [comment]
```C#
            using (var xClient = new DHCPClient())
            {
                if (xClient.SendDiscoverPacket() != -1)
                {
                    xClient.Close();
                }
                else
                {
                    xClient.Close();
                    log.ERROR("Something went wrong when connecting to the internet. OS halted.");
                    while (true)
                    {
                        System.Threading.Thread.Sleep(5000);
                    }
                }
            }
```

**Comment by valentinbreiz** [comment]
I published a fix, could you try it before merging?

**Comment by poggingfish** [comment]
Yes. Just give me a moment

**Comment by poggingfish** [comment]
Yes. Just give me a moment

**Comment by poggingfish** [comment]
Yeah still nothing. Still getting 0.0.0.0 😓

**Comment by Kiirx** [comment]
here's mine
[pcapKiirx.zip](https://github.com/CosmosOS/Cosmos/files/8023035/pcapKiirx.zip)

**Comment by Kiirx** [comment]
@valentinbreiz cant build with branch fix-dhcp offer

**Comment by Kiirx** [comment]
https://www.toptal.com/developers/hastebin/zubucoboxe.sql

**Comment by Kiirx** [comment]
idk how it also broke on main branch

**Comment by Kiirx** [comment]
https://www.toptal.com/developers/hastebin/yucaniwobi.sql

**Comment by Kiirx** [comment]
related to #2102

**Comment by Kiirx** [comment]
okay seems that he found a working fix

**Comment by fusedevgithub** [comment]
> okay seems that he found a working fix

that working for you?

**Comment by Kiirx** [comment]
yes it boots fine

**Comment by valentinbreiz** [comment]
Hello guys, could someone try the new commits I pushed in the DHCP Fixes pull request?

**Comment by poggingfish** [comment]
Any updates on this issue

**Comment by MishaTY** [comment]
Is this fixed?

**Comment by Kiirx** [comment]
Yes

**Comment by Kiirx** [comment]
This problem is still happening, but I discovered that the problem is VMware and not Cosmos since it works fine on virtualbox.

This is on **VMware**:
![image](https://user-images.githubusercontent.com/43090601/162562663-959eca68-cb42-45a3-a3e3-67607be29271.png)
This is on **VirtualBox**:
![image](https://user-images.githubusercontent.com/43090601/162562705-588ee500-141b-44ce-9d41-4b5e998759d7.png)

**Comment by valentinbreiz** [comment]
Did you configured VMWare to NAT?

**Comment by Kiirx** [comment]
> Did you configured VMWare to NAT?

its Cosmos default settings

**Comment by Kiirx** [comment]
it always set the network config to this 
![image](https://user-images.githubusercontent.com/43090601/162577729-7db33335-a268-404b-8ed9-ec686227ab14.png)

**Comment by Kiirx** [comment]
![image](https://user-images.githubusercontent.com/43090601/164891042-5cba9423-6f38-4292-8afd-e9dbd83783ed.png)
wait what now it works
