### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by SMGamingCoder** [CosmosOS/Cosmos#773]
So I got another error I am currently unable to solve. I currently think that I need a .dll file.

Severity	Code	Description	Project	File	Line	Suppression State
Error		An error occurred: System.TypeInitializationException: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.DllNotFoundException: Unable to load DLL 'e_sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_libversion_number()
   at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
   at SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
   at SQLitePCL.Batteries_V2.Init()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Data.Sqlite.Utilities.BundleInitializer.Initialize()
   at Microsoft.Data.Sqlite.SqliteConnection..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)
   at Cosmos.Debug.Symbols.DebugInfo..ctor(String aPathname, Boolean aCreate, Boolean aCreateIndexes)
   at Cosmos.Debug.Symbols.ObjDump.ExtractMapSymbolsForElfFile(String debugFile, String mapFile)
   at Cosmos.Build.MSBuild.ExtractMapFromElfFile.Execute()	CosmosKernel2Boot	C:\Users\Logan Rios\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets	75

**Comment by SMGamingCoder** [comment]
OOHOHOOHOHOHOOHOHOH

Found out what happened. This bug happens when you don't have VMWARE installed.

**Comment by Arawn-Davies** [comment]
This bug may have happened with you because of VMWare not being installed, but I was getting this issue even with VMWare player and Workstation installed, that's why I've been using the user kit lately.

would the Cosmos.targets need that fix for the userkit as well on the devkit? 
The bit of code I'm referring to is this:
```xml
<ImplicitlyExpandNETStandardFacades>False</ImplicitlyExpandNETStandardFacades>
<DesignTimeBuild>True</DesignTimeBuild>
<ProjectAssetsFile>NULL</ProjectAssetsFile>
```

**Comment by Arawn-Davies** [comment]
Building with Cosmos after installing .NET Core 2.0 and building SQLite 2.0.0 https://github.com/aspnet/Microsoft.Data.Sqlite/releases/tag/rel%2F2.0.0 appears to fix this issue, need to check whether esqlite_3 is copied to output however

**Comment by piixx** [comment]
@Arawn-Davies 

Built, still erroring.

**Comment by piixx** [comment]
You have to restart Visual Studio to get it to work.

**Comment by Arawn-Davies** [comment]
Seems to work on and off, I'll try building .NET Core manually with the replacement SQLite used, hopefully they'll be able to sort something out before not too long

**Comment by LegitSoulja** [comment]
Seems like a package is not being installed with the latest release. Manually install this package simply using the package manager, https://www.nuget.org/packages/Microsoft.Data.Sqlite/.

This issue can be closed.

**Comment by LegitSoulja** [comment]
Ah, vs keeps fooling me :/. I'll resolve this shortly.

**Comment by Arawn-Davies** [comment]
Fixed in commit https://github.com/CosmosOS/Cosmos/commit/3edc13ba7b6656368c70a13ab08d78e923195210

**Comment by expeehaa** [comment]
@Arawn-Davies i have the same problem with the latest version of dev kit compiled and installed just about an hour ago. I tried your solution above with building SQLite 2.0.0 didn't work. Installing VMWare Player didn't help, too (how should it help?!), but as someone mentioned it, it was worth trying. 
Either I'm doing something completely wrong or the problem really isn't solved.
